### ISSUE TITLE
Describe Security Concept

### ISSUE THREAD

**Issue by vanthome** [djannot/mesos-vulcanproxy#1]
Hi,
I really like your approach to this but I think the security implications should be documented a bit more or there has to be some instructions how to secure it.
Because as it currently is, you cannot use this for a multi-tenancy cloud with untrusted containers, as everyone can read/ write to etcd and marathon -- or am I wrong?
The alternative would be to have a management network where maraton, etcd and vulcand are exposing their APIs.
Thanks

**Comment by djannot** [comment]
I've added the following comment:
This tool isn't "production ready" and was developped to show end to end automation.

You're right, there's clearly a lack of security if it's used as-is.
